<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.tibco.rest.test.DataDrivenTestCases"
           tests="506"
           failures="506"
           errors="0"
           skipped="0"
           time="372.243">
  <properties />
      <testcase name="ROLE-05" time="0.633">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;Auto Role Edited  you have entered  is already in use&quot; : Actual value is &quot;Auto Role Edited  you have entered  is already in use&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "Auto Role Edited  you have entered  is already in use" : Actual value is "Auto Role Edited  you have entered  is already in use"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="USER-14" time="0.663">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;The password you have entered is same as the earlier&quot; : Actual value is &quot;The password you have entered is same as the earlier&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "The password you have entered is same as the earlier" : Actual value is "The password you have entered is same as the earlier"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="PCCEC-07" time="0.729">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;Name  you have entered  is already in use&quot; : Actual value is &quot;Name  you have entered  is already in use&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "Name  you have entered  is already in use" : Actual value is "Name  you have entered  is already in use"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="RNROLEERROR-05" time="0.671">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;RosettaNet Role Name  you have entered  is already in use&quot; : Actual value is &quot;RosettaNet Role Name  you have entered  is already in use&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "RosettaNet Role Name  you have entered  is already in use" : Actual value is "RosettaNet Role Name  you have entered  is already in use"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="OPERATION-17" time="0.649">
            <failure type="java.lang.AssertionError"
                  message="Unable to store response string to variable or couldn&apos;t received response."
              >
<![CDATA[java.lang.AssertionError: Unable to store response string to variable or couldn't received response.
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:415)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-14" time="0.688">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;CMName&quot; : Actual value is &quot;&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "CMName" : Actual value is ""
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SCC-06" time="0.638">
            <failure type="java.lang.AssertionError"
                  message="Unable to store response string to variable or couldn&apos;t received response."
              >
<![CDATA[java.lang.AssertionError: Unable to store response string to variable or couldn't received response.
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:415)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="USER-06" time="0.658">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;Auto user Edited&quot; : Actual value is &quot;Auto user&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "Auto user Edited" : Actual value is "Auto user"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="OPERATIONS-RN013" time="0.794">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;RosettaNet&quot; : Actual value is &quot;Gateway&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "RosettaNet" : Actual value is "Gateway"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="USER-17" time="0.640">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;Invalid credentials&quot; : Actual value is &quot;Invalid credentials&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "Invalid credentials" : Actual value is "Invalid credentials"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="ENABLEDPROTOCOL-03" time="0.735">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;EZComm&quot; : Actual value is &quot;EDIFACT&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "EZComm" : Actual value is "EDIFACT"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="OPERATIONS-RN016" time="0.652">
            <failure type="java.lang.AssertionError"
                  message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:344)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="OPERATIONS-RN020" time="0.005">
            <failure type="java.net.URISyntaxException"
                  message="Illegal character in path at index 55: http://10.102.16.61:30001/cms/v1/operations/RosettaNet/[]"
              >
<![CDATA[java.net.URISyntaxException: Illegal character in path at index 55: http://10.102.16.61:30001/cms/v1/operations/RosettaNet/[]
  java.net.URI$Parser.fail(Unknown Source)
  java.net.URI$Parser.checkChars(Unknown Source)
  java.net.URI$Parser.parseHierarchical(Unknown Source)
  java.net.URI$Parser.parse(Unknown Source)
  java.net.URI.<init>(Unknown Source)
  io.restassured.internal.http.URIBuilder.convertToURI(URIBuilder.java:91)
  io.restassured.internal.http.URIBuilder$convertToURI.call(Unknown Source)
  io.restassured.internal.RequestSpecificationImpl.generateRequestUriForLogging(RequestSpecificationImpl.groovy:1193)
  sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
  io.restassured.internal.RequestSpecificationImpl.newFilterContext(RequestSpecificationImpl.groovy:1154)
  sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1729)
  sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
  sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:170)
  io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:210)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-11" time="0.616">
            <failure type="java.lang.AssertionError"
                  message="Response Code is 500"
              >
<![CDATA[java.lang.AssertionError: Response Code is 500
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:460)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-05" time="0.659">
            <failure type="java.lang.AssertionError"
                  message="Response Code is 500"
              >
<![CDATA[java.lang.AssertionError: Response Code is 500
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:460)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="DOMAINTYPE-07" time="0.709">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;Auto Domain Type  you have entered  is already in use&quot; : Actual value is &quot;Auto Domain Type  you have entered  is already in use&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "Auto Domain Type  you have entered  is already in use" : Actual value is "Auto Domain Type  you have entered  is already in use"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="USER-09" time="1.692">
            <failure type="java.lang.AssertionError"
                  message="Expected value should not be &quot;&quot; : Actual value is &quot;&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should not be "" : Actual value is ""
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-22" time="0.637">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;CMName1&quot; : Actual value is &quot;&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "CMName1" : Actual value is ""
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="PCCEC-10" time="1.223">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;sccode1 you have entered  is already in use&quot; : Actual value is &quot;sccode1 you have entered  is already in use&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "sccode1 you have entered  is already in use" : Actual value is "sccode1 you have entered  is already in use"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="DOMAINPAIRSRN-06" time="0.634">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;1&quot; : Actual value is &quot;0&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "1" : Actual value is "0"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="OPERATION-01" time="0.805">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;EZComm&quot; : Actual value is &quot;EDIFACT&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "EZComm" : Actual value is "EDIFACT"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="OPERATIONS-RN012" time="0.659">
            <failure type="java.lang.AssertionError"
                  message="Unable to store response string to variable or couldn&apos;t received response."
              >
<![CDATA[java.lang.AssertionError: Unable to store response string to variable or couldn't received response.
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:415)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-08" time="0.634">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;CMName&quot; : Actual value is &quot;&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "CMName" : Actual value is ""
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-17" time="0.624">
            <failure type="java.lang.AssertionError"
                  message="Response Code is 500"
              >
<![CDATA[java.lang.AssertionError: Response Code is 500
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:460)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="RNROLEERROR-02" time="0.692">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;RN Role Test you have entered  is already in use&quot; : Actual value is &quot;RN Role Test you have entered  is already in use&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "RN Role Test you have entered  is already in use" : Actual value is "RN Role Test you have entered  is already in use"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-23" time="0.620">
            <failure type="java.lang.AssertionError"
                  message="Response Code is 500"
              >
<![CDATA[java.lang.AssertionError: Response Code is 500
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:460)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="DOMAINPAIRSRN-04" time="0.005">
            <failure type="java.net.URISyntaxException"
                  message="Illegal character in path at index 45: http://10.102.16.61:30001/cms/v1/domainPairs/[]"
              >
<![CDATA[java.net.URISyntaxException: Illegal character in path at index 45: http://10.102.16.61:30001/cms/v1/domainPairs/[]
  java.net.URI$Parser.fail(Unknown Source)
  java.net.URI$Parser.checkChars(Unknown Source)
  java.net.URI$Parser.parseHierarchical(Unknown Source)
  java.net.URI$Parser.parse(Unknown Source)
  java.net.URI.<init>(Unknown Source)
  io.restassured.internal.http.URIBuilder.convertToURI(URIBuilder.java:91)
  io.restassured.internal.http.URIBuilder$convertToURI.call(Unknown Source)
  io.restassured.internal.RequestSpecificationImpl.generateRequestUriForLogging(RequestSpecificationImpl.groovy:1193)
  sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
  io.restassured.internal.RequestSpecificationImpl.newFilterContext(RequestSpecificationImpl.groovy:1154)
  sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1729)
  sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
  sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:170)
  io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:210)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="TOutbound8" time="0.845">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;The Transport name http_rn  you have entered  is already in use&quot; : Actual value is &quot;The Transport name http_rn  you have entered  is already in use&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "The Transport name http_rn  you have entered  is already in use" : Actual value is "The Transport name http_rn  you have entered  is already in use"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="TOutbound13" time="0.833">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;The Transport name https_rn  you have entered  is already in use&quot; : Actual value is &quot;The Transport name https_rn  you have entered  is already in use&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "The Transport name https_rn  you have entered  is already in use" : Actual value is "The Transport name https_rn  you have entered  is already in use"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-02" time="0.637">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;CMName&quot; : Actual value is &quot;&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "CMName" : Actual value is ""
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-16" time="1.620">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;CMName1&quot; : Actual value is &quot;&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "CMName1" : Actual value is ""
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="PARTNER-15" time="0.660">
            <failure type="java.lang.AssertionError"
                  message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="OPERATIONS-RN023" time="0.645">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;edited&quot; : Actual value is &quot;edited&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "edited" : Actual value is "edited"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="OPERATION-22" time="0.740">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;Auto node0 Edited&quot; : Actual value is &quot;Auto node0&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "Auto node0 Edited" : Actual value is "Auto node0"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="TOutbound15" time="0.008">
            <failure type="java.net.URISyntaxException"
                  message="Illegal character in path at index 53: http://10.102.16.61:30001/cms/v1/transports/outbound/[]"
              >
<![CDATA[java.net.URISyntaxException: Illegal character in path at index 53: http://10.102.16.61:30001/cms/v1/transports/outbound/[]
  java.net.URI$Parser.fail(Unknown Source)
  java.net.URI$Parser.checkChars(Unknown Source)
  java.net.URI$Parser.parseHierarchical(Unknown Source)
  java.net.URI$Parser.parse(Unknown Source)
  java.net.URI.<init>(Unknown Source)
  io.restassured.internal.http.URIBuilder.convertToURI(URIBuilder.java:91)
  io.restassured.internal.http.URIBuilder$convertToURI.call(Unknown Source)
  io.restassured.internal.RequestSpecificationImpl.generateRequestUriForLogging(RequestSpecificationImpl.groovy:1193)
  sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
  io.restassured.internal.RequestSpecificationImpl.newFilterContext(RequestSpecificationImpl.groovy:1154)
  sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1729)
  sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
  sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy:178)
  io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:214)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="USER-12" time="0.640">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;false&quot; : Actual value is &quot;false&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "false" : Actual value is "false"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="TOutbound14" time="0.004">
            <failure type="java.net.URISyntaxException"
                  message="Illegal character in path at index 53: http://10.102.16.61:30001/cms/v1/transports/outbound/[]"
              >
<![CDATA[java.net.URISyntaxException: Illegal character in path at index 53: http://10.102.16.61:30001/cms/v1/transports/outbound/[]
  java.net.URI$Parser.fail(Unknown Source)
  java.net.URI$Parser.checkChars(Unknown Source)
  java.net.URI$Parser.parseHierarchical(Unknown Source)
  java.net.URI$Parser.parse(Unknown Source)
  java.net.URI.<init>(Unknown Source)
  io.restassured.internal.http.URIBuilder.convertToURI(URIBuilder.java:91)
  io.restassured.internal.http.URIBuilder$convertToURI.call(Unknown Source)
  io.restassured.internal.RequestSpecificationImpl.generateRequestUriForLogging(RequestSpecificationImpl.groovy:1193)
  sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
  io.restassured.internal.RequestSpecificationImpl.newFilterContext(RequestSpecificationImpl.groovy:1154)
  sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1729)
  sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
  sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:170)
  io.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:210)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="DOMAINPAIRSRN-07" time="0.635">
            <failure type="java.lang.AssertionError"
                  message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="INSTALLED PROTOCOLS-01" time="0.640">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;RosettaNet&quot; : Actual value is &quot;EZComm&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "RosettaNet" : Actual value is "EZComm"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-10" time="0.629">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;CMName1&quot; : Actual value is &quot;&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "CMName1" : Actual value is ""
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="DOMAINPAIRSRN-05" time="0.008">
            <failure type="java.net.URISyntaxException"
                  message="Illegal character in path at index 45: http://10.102.16.61:30001/cms/v1/domainPairs/[]"
              >
<![CDATA[java.net.URISyntaxException: Illegal character in path at index 45: http://10.102.16.61:30001/cms/v1/domainPairs/[]
  java.net.URI$Parser.fail(Unknown Source)
  java.net.URI$Parser.checkChars(Unknown Source)
  java.net.URI$Parser.parseHierarchical(Unknown Source)
  java.net.URI$Parser.parse(Unknown Source)
  java.net.URI.<init>(Unknown Source)
  io.restassured.internal.http.URIBuilder.convertToURI(URIBuilder.java:91)
  io.restassured.internal.http.URIBuilder$convertToURI.call(Unknown Source)
  io.restassured.internal.RequestSpecificationImpl.generateRequestUriForLogging(RequestSpecificationImpl.groovy:1193)
  sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
  io.restassured.internal.RequestSpecificationImpl.newFilterContext(RequestSpecificationImpl.groovy:1154)
  sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1729)
  sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1737)
  sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
  groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
  groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
  io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:48)
  org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:58)
  org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
  io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy:178)
  io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:214)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-20" time="0.630">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;CMName&quot; : Actual value is &quot;&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "CMName" : Actual value is ""
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="LOCATIONERROR-04" time="0.627">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;Admin Office  you have entered  is already in use&quot; : Actual value is &quot;Admin Office  you have entered  is already in use&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "Admin Office  you have entered  is already in use" : Actual value is "Admin Office  you have entered  is already in use"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="UserGroup-02" time="0.618">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;Groupname Auto User group  you have entered  is already in use.&quot; : Actual value is &quot;Groupname Auto User group  you have entered  is already in use.&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "Groupname Auto User group  you have entered  is already in use." : Actual value is "Groupname Auto User group  you have entered  is already in use."
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="OPERATIONS-RN024" time="0.645">
            <failure type="java.lang.AssertionError"
                  message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="IBTProtocol-12" time="0.621">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;EMAIL&quot; : Actual value is &quot;[&quot;EMAIL&quot;,&quot;FILE&quot;,&quot;FTP&quot;,&quot;HTTP&quot;]&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "EMAIL" : Actual value is "["EMAIL","FILE","FTP","HTTP"]"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="USER-15" time="0.652">
            <failure type="java.lang.AssertionError"
                  message="Expected value should contains &quot;The password you have entered does not match&quot; : Actual value is &quot;The password you have entered does not match&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should contains "The password you have entered does not match" : Actual value is "The password you have entered does not match"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="PCCEC-06" time="0.871">
            <failure type="java.lang.AssertionError"
                  message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:344)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="SR-04" time="0.716">
            <failure type="java.lang.AssertionError"
                  message="Expected value should be &quot;CMName1&quot; : Actual value is &quot;&quot;"
              >
<![CDATA[java.lang.AssertionError: Expected value should be "CMName1" : Actual value is ""
  com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
  com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
  com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
  com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
  sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.TestNG.privateMain(TestNG.java:1442)
  org.testng.TestNG.main(TestNG.java:1411)
]]>
      </failure>

          </testcase>
      <testcase name="OPERATIONS-RN001" time="0.657">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RNROLEERROR-06" time="0.624">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBDHOST-02" time="0.793">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGS-06" time="0.651">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-13" time="0.647">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Delete-BZAgreement-14" time="0.680">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN014" time="0.726">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-08" time="0.691">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ROLE-09" time="0.664">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TBizAgreement5" time="0.791">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-CreateProtocolBind-11" time="0.799">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-ProtocolBinding" time="0.763">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOLX12-04" time="0.617">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-05" time="0.796">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-04" time="0.659">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-01" time="0.782">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="GSInfor-3" time="0.614">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGS-21" time="0.762">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TPartner2" time="0.801">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-02" time="0.694">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OUTBOUNDTRANSPORTX12-01" time="0.989">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TOutbound6" time="0.886">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-10" time="0.629">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPERN-02" time="0.832">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BAErrorCode-04" time="0.717">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBDBIZID-04" time="0.799">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-20" time="0.906">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-03" time="0.787">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-OverrideOperationsBinding-ost1" time="0.634">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RosettaNetRoles-Search-6" time="0.608">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-2" time="0.623">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="MsgBus-1" time="0.775">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-05" time="0.734">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-11" time="0.789">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OUTBOUNDTRANSPORT-07" time="0.626">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-01" time="0.682">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="GatewayService-3" time="0.832">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="THOST23" time="0.684">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-16" time="0.631">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BIZAGREEMENTX12-01" time="0.765">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-18" time="0.682">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BIZAGREEMENT-21" time="0.668">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNERLOCATION-02" time="0.635">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPE-05" time="0.629">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN017" time="0.906">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-13" time="0.638">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OUTBOUNDTRANSPORT-02" time="0.663">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ROLE-03" time="0.629">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-04" time="0.754">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-Group02" time="0.698">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-06" time="0.620">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-01" time="0.703">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Outboundtrans-8" time="0.903">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-12" time="0.653">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RBERROR-05" time="0.634">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-11" time="0.624">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGSX12-06" time="0.629">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="MsgBus-6" time="0.639">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="MsgBus-4" time="0.649">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-14" time="0.609">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RBERROR-06" time="0.665">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Host-4" time="0.677">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="LOCATION-02" time="0.642">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="LOCATION-03" time="0.638">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-09" time="0.617">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="CONTACT-05" time="0.667">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBD-05" time="1.094">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-14" time="0.673">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN021" time="0.699">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPE-04" time="0.703">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-Group01" time="0.709">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TBizAgreement21" time="0.648">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-OverrideOperationsBinding-ast2" time="0.630">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="IBTProtocol-2" time="0.867">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRSX12-03" time="0.758">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGS-22" time="0.642">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Delete-partner-16" time="0.649">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-21" time="0.853">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-OperationsRequestResponsetransaction" time="0.845">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="LOCATIONERROR-03" time="0.717">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-05" time="0.648">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-20" time="0.888">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OUTBOUNDTRANSPORT-20" time="0.932">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-11" time="0.634">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOST-05" time="0.670">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Create-operation-1" time="0.733">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-05" time="0.672">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-10" time="0.615">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRS-06" time="0.628">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOSTBA-04" time="0.683">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOSTBA-03" time="0.622">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-EnableProtocol-8" time="0.898">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ROLE-10" time="0.696">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-19" time="0.775">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OUTBOUNDTRANSPORT-04" time="0.661">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="INBOUNDTRANSPORT-01" time="0.622">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-OperationsNotifytransaction" time="0.962">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-04" time="0.638">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN006" time="0.940">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPERN-06" time="0.660">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-27" time="0.667">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SCC-05" time="0.649">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN026" time="0.706">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SCC-03" time="0.718">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="IBTProtocol-7" time="0.812">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBDPARTNER-05" time="0.633">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RNROLEERROR-03" time="0.682">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OUTBOUNDTRANSPORT-03" time="0.632">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RN-CreatePARTNER-8" time="0.755">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNERX12-01" time="0.779">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIOn-12" time="0.647">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="MBERROR-01" time="0.622">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGS-05" time="0.779">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN022" time="0.644">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-OperationsNode0" time="0.731">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-25" time="0.635">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPERN-08" time="0.642">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="INBOUNDTRANSPORT-05" time="0.651">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-23" time="0.820">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-06" time="0.652">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOLX12-07" time="0.603">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Outboundtrans-8" time="0.896">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-10" time="0.646">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPE-08" time="0.656">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-12" time="0.612">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-06" time="0.905">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRS-09" time="0.809">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="CONTACT-02" time="0.661">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-02" time="0.622">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOLX12-06" time="0.645">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-19" time="0.664">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-12" time="0.620">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-OverrideOperationsBinding-tt2" time="0.642">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-20" time="0.852">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRS-01" time="0.680">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-CreateBizAgre-7" time="0.759">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="MsgBus-5" time="0.775">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RBERROR-01" time="0.657">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-09" time="0.667">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TPartner22" time="0.651">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-04" time="7.447">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGSX12-05" time="0.623">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-2" time="0.653">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BAErrorCode-05" time="0.641">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-03" time="0.650">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="INBOUNDTRANSPORT-02" time="0.657">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OUTBOUNDTRANSPORT-05" time="0.632">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRSRN-02" time="0.747">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-02" time="0.884">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-Delete BA" time="0.647">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="IBTProtocol-11" time="0.819">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-07" time="0.876">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN002" time="0.727">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="GatewayService-5" time="0.676">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRSRN-03" time="0.624">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN027" time="0.642">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BIZAGREEMENT-05" time="0.640">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBD-04" time="0.945">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-13" time="0.716">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-5" time="0.663">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="IBTProtocol-3" time="1.414">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OUTBOUNDTRANSPORT-09" time="0.852">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-03" time="0.740">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-01" time="0.807">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="GatewayService-4" time="0.676">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RolesBinding-Search-12" time="0.612">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGS-02" time="0.798">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-16" time="0.683">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-EnableProtocol-6" time="0.876">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGS-04" time="0.704">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-10" time="0.679">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-25" time="0.696">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-Group01" time="0.758">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOST-04" time="0.631">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCode4" time="0.613">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TEnableProtocolPartner4" time="1.553">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-EnableProtocol-7" time="0.958">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-OutboundTransportRN" time="0.931">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-Host" time="0.807">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-18" time="0.646">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-13" time="0.833">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRS-10" time="0.631">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-07" time="1.123">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-04" time="0.710">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-CreateProtocolBind-9" time="0.860">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Create-operation-1" time="0.631">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-CreateProtocolBind-10" time="0.876">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-24" time="0.686">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOLX12-01" time="0.953">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Host-4" time="0.733">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPE-09" time="0.627">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGS-01" time="0.821">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BIZAGREEMENT-01" time="0.770">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-03" time="0.778">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-Group04" time="0.625">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="GSInfor-1" time="0.685">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBDOUTBTRANS-05" time="0.982">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOSTS-21" time="0.717">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RN-DeletePARTNER-13" time="0.656">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGSX12-04" time="0.783">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SCC-07" time="0.637">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-EnableProtocol-6" time="0.910">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-09" time="0.686">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-08" time="0.611">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RBERROR-03" time="0.729">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-22" time="0.665">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Delete-BZAgreement-18" time="0.672">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Create-Syncoperation-3" time="0.894">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ROLE-02" time="0.648">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="LOCATION-01" time="0.901">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-21" time="0.684">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Create-operation-2" time="0.692">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="MsgBus-3" time="1.344">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRSX12-06" time="0.779">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="Feature-01" time="1.542">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Delete-partner-20" time="0.691">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BIZAGREEMENT-20" time="0.824">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-15" time="0.678">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RNROLEERROR-07" time="0.631">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPE-02" time="0.649">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOSTX12-01" time="0.703">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-06" time="0.609">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TOutbound17" time="0.640">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN015" time="0.790">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNERBA-01" time="0.835">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RosettaNetRoles-Get-2" time="0.625">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOLX12-03" time="0.845">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ROLE-07" time="0.643">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="INBOUNDTRANSPORT-04" time="0.651">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="LOCATIONERROR-02" time="0.739">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-19" time="0.767">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN025" time="0.656">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="IBTProtocol-10" time="0.832">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPE-06" time="0.618">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Outboundtrans-10" time="0.761">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="LOCATION-08" time="0.642">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN010" time="0.662">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-09" time="0.630">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-OverrideOperationsBinding-tt1" time="0.631">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN004" time="0.629">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ROLE-06" time="0.624">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="CONTACT-01" time="0.765">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="CONTACT-07" time="0.625">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RNROLEERROR-04" time="0.625">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPE-03" time="0.649">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRS-05" time="0.786">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPERN-09" time="0.654">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-Group03" time="0.628">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RosettaNetRoles-GetAll-7" time="0.626">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-Partner" time="0.768">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TOutbound7" time="0.644">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-11" time="0.623">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-11" time="0.646">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOSTBA-02" time="0.805">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="Role_Group" time="0.624">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNERLOCATION-01" time="0.778">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRSX12-04" time="0.753">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOSTBA-05" time="0.928">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TEnableProtocolHost3" time="0.899">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCode2" time="0.633">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-05" time="0.822">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCode6" time="0.635">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="IBTProtocol-4" time="0.826">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCode3" time="0.705">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-Group02" time="0.770">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGSX12-01" time="0.940">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="CONTACT-08" time="0.656">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-09" time="0.632">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-Delete Partner" time="0.646">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RolesBinding-Search-11" time="0.607">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGS-03" time="0.646">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-06" time="0.698">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRS-04" time="0.630">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-CreateOperationBinding" time="0.804">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBDBIZID-05" time="1.298">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRSX12-01" time="0.792">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-08" time="0.813">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-32" time="0.643">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOST-03" time="0.772">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TOutbound16" time="0.636">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="INSTALLED PROTOCOLS-02" time="0.715">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-OverrideOperationsBinding-ast1" time="0.642">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-OverrideOperationsBinding-ost2" time="0.627">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-21" time="0.620">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SCC-02" time="0.637">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPERN-07" time="0.632">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="GatewayService-2" time="0.671">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOST-20" time="0.890">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-8" time="0.858">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Delete-Operation-16" time="0.620">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-1" time="0.781">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="IBTProtocol-9" time="0.800">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="LOCATION-04" time="0.822">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-Enableprotocol" time="0.875">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-24" time="0.625">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="GSInfor-2" time="0.618">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="EnableRNProtocol-9" time="1.025">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RosettaNetRoles-Create-1" time="0.701">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="LOCATION-05" time="0.620">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNERBA-04" time="0.636">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="LOCATION-06" time="0.646">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="CONTACT-04" time="0.822">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RBERROR-04" time="0.722">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRSX12-02" time="0.778">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPERN-03" time="0.741">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-02" time="0.651">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-04" time="0.877">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SCC-01" time="0.732">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RosettaNetRoles-Update-3" time="0.831">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-01" time="1.179">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPERN-04" time="0.646">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-16" time="0.644">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="GatewayService-1" time="0.777">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="LOCATION-07" time="0.930">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-12" time="0.642">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOLX12-05" time="0.831">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ROLE-01" time="0.722">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRS-03" time="0.647">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-Enableprotocol1" time="1.015">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOLBA-01" time="0.904">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBD-08" time="0.944">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Delete-host-15" time="0.833">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRS-07" time="0.630">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-01" time="0.857">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="INBOUNDTRANSPORT-03" time="0.814">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="IBTProtocol-5" time="0.812">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RNROLEERROR-01" time="0.715">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-31" time="0.640">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BIZAGREEMENT-06" time="0.643">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-11" time="0.618">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-PARTNER-5" time="0.644">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-3" time="0.828">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RNROLEERROR-08" time="0.634">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="IBTProtocol-6" time="0.863">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Create-Syncoperation-3" time="0.847">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-16" time="0.831">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BAErrorCode-06" time="0.630">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOLX12-08" time="0.623">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RosettaNetRoles-Get-4" time="0.611">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNERBA-03" time="0.644">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-26" time="0.677">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-15" time="0.628">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNERBA-02" time="0.802">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BIZAGREEMENT-03" time="0.662">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-10" time="0.628">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-30" time="0.638">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-6" time="0.859">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-18" time="0.790">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGS-20" time="0.799">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-11" time="0.661">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="CONTACT-03" time="0.793">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TOutbound9" time="0.704">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="THOST1" time="0.737">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Delete-Operation-17" time="0.618">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNERX12-02" time="0.637">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SCC-04" time="0.640">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRS-11" time="0.617">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCode5" time="0.625">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRS-08" time="0.658">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRSRN-01" time="0.623">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-12" time="0.794">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-30" time="1.167">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN003" time="0.661">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-21" time="0.783">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-CreateProtocolBind-10" time="0.844">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN011" time="0.633">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-17" time="0.674">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ROLE-08" time="0.638">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-24" time="0.697">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BIZAGREEMENT-04" time="0.635">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-05" time="0.614">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="LOCATIONERROR-01" time="0.859">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RosettaNetRoles-Delete-15" time="0.682">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-12" time="0.699">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RBERROR-02" time="0.999">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN019" time="0.751">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-PARTNER-5" time="0.749">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-07" time="0.667">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNER-02" time="0.636">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN018" time="0.730">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN009" time="0.674">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BAErrorCode-03" time="0.730">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-BA" time="0.743">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Delete-Operation-12" time="0.782">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN007" time="0.698">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPE-01" time="0.758">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-15" time="0.630">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RolesBinding-Create-10" time="0.752">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="MsgBus-2" time="0.652">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="IBTProtocol-1" time="0.794">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-9" time="0.666">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-4" time="0.667">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ROLE-04" time="0.665">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-03" time="0.655">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-Delete Host" time="0.644">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPERN-05" time="0.623">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINTYPERN-01" time="0.723">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RolesBinding-Delete-14" time="0.629">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-CreateProtocolBind-15" time="0.671">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBD-07" time="0.900">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-29" time="0.644">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN008" time="0.655">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-Delete operation node0" time="0.626">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-15" time="0.617">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Create-operation-2" time="0.781">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBDPARTNER-01" time="0.748">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="IBTProtocol-8" time="0.831">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OUTBOUNDTRANSPORT-01" time="0.833">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOLX12-02" time="0.958">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOSTX12-02" time="0.645">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGSX12-03" time="0.673">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ROLE-08" time="0.660">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BAErrorCode-02" time="0.772">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-CreateProtocolBind-10" time="0.906">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOST-02" time="0.633">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="SR-07" time="0.816">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="CONTACT-06" time="0.645">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATIONS-RN005" time="0.866">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-CreateProtocolBind-11" time="0.954">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-28" time="0.630">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-CreateProtocolBind-9" time="0.785">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOLX12-09" time="0.629">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-14" time="0.661">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-18" time="0.818">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-OperationsNode1" time="0.647">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBDHOST-04" time="0.651">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBINDINGSX12-02" time="0.934">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-7" time="0.695">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRS-02" time="0.773">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-07" time="0.623">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="DOMAINPAIRSX12-05" time="0.775">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="UserGroup-12" time="0.623">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROXY-23" time="0.795">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="RosettaNetRoles-Search-5" time="0.632">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-08" time="0.707">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCEC-08" time="0.681">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PCCode1" time="0.761">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="InstalledTProtocols-1" time="0.708">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PROTOCOLBD-06" time="0.852">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-03" time="0.637">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="PARTNERBA-05" time="0.660">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BIZAGREEMENT-07" time="0.642">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Delete-Operation-13" time="0.624">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OBRN-DeleteOperationBinding" time="0.664">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BIZAGREEMENT-02" time="0.748">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TOutbound10" time="0.629">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TOutbound11" time="0.631">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="BUSINESSAGREEMENTX12-02" time="0.646">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-CreateBizAgre-7" time="0.762">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OPERATION-19" time="0.850">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-OverrideOperationsBinding1" time="0.699">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="TOutbound12" time="0.782">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOSTBA-01" time="0.705">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="HOST-01" time="0.785">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="USER-07" time="0.675">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="ENABLEDPROTOCOL-07" time="0.724">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
      <testcase name="OB-Delete-host-19" time="0.668">
            <failure type="Unknown"
                  message="Unknown"
              />
          </testcase>
  
  
  
</testsuite>
